In [7]:
import numpy as np

In [27]:
class NeuralNetwork():
    def __init__(self):
        np.random.seed(1)
        
        # setting the number of nodes 
        l2 = 5
        l3 = 4
        
        # initialize 3 weights
        self.synaptic_weights1 = 2 * np.random.random((3,l2)) - 1
        self.synaptic_weights2 = 2 * np.random.random((l2,l3)) - 1
        self.synaptic_weights3 = 2 * np.random.random((l3,1)) - 1
        
        self.activation_function = lambda x: 1 / (1 + np.exp(-x))
        self.derivative = lambda x: x * (1-x)
        
    def train(self, X, y, iterations):
        # Convert inputs list to 2d array
        #X = np.array(X, ndmin=2)
        #y = np.array(y, ndmin=2)
        
        for iter in range(iterations):
            # feed forward
            a2 = self.activation_function(np.dot(X, self.synaptic_weights1))
            a3 = self.activation_function(np.dot(a2, self.synaptic_weights2))
            output = self.activation_function(np.dot(a3, self.synaptic_weights3))
            
            # error
            delta4 = (y - output)*self.derivative(output)
            delta3 = np.dot(self.synaptic_weights3,delta4.T)*self.derivative(a3).T
            delta2 = np.dot(self.synaptic_weights2,delta3)*self.derivative(a2).T
            
            # adjustments
            adjustment3 = np.dot(a3.T, delta4)
            adjustment2 = np.dot(a2.T, delta3.T)
            adjustment1 = np.dot(X.T, delta2.T)
            
            # update weights
            self.synaptic_weights1 += adjustment1
            self.synaptic_weights2 += adjustment2
            self.synaptic_weights3 += adjustment3
            
    def run(self, X):
        # forward pass
        a2 = self.activation_function(np.dot(X, self.synaptic_weights1))
        a3 = self.activation_function(np.dot(a2, self.synaptic_weights2))
        output = self.activation_function(np.dot(a3, self.synaptic_weights3))
        
        return output
            

In [28]:
NN = NeuralNetwork()

print("Random starting synaptic weights (layer 1): ")
print(NN.synaptic_weights1)
print("Random starting synaptic weights (layer 2): ")
print(NN.synaptic_weights2)
print("Random starting synaptic weights (layer 3): ")
print(NN.synaptic_weights3)

inputs = np.array([[0,0,1],[1,1,1],[1,0,1],[0,1,1]])
targets = np.array([[0,1,1,0]]).T

NN.train(inputs,targets, 10000)

print ("\nNew synaptic weights (layer 1) after training: ")
print (NN.synaptic_weights1)
print ("\nNew synaptic weights (layer 2) after training: ")
print (NN.synaptic_weights2)
print ("\nNew synaptic weights (layer 3) after training: ")
print (NN.synaptic_weights3)

Random starting synaptic weights (layer 1): 
[[-0.16595599  0.44064899 -0.99977125 -0.39533485 -0.70648822]
 [-0.81532281 -0.62747958 -0.30887855 -0.20646505  0.07763347]
 [-0.16161097  0.370439   -0.5910955   0.75623487 -0.94522481]]
Random starting synaptic weights (layer 2): 
[[ 0.34093502 -0.1653904   0.11737966 -0.71922612]
 [-0.60379702  0.60148914  0.93652315 -0.37315164]
 [ 0.38464523  0.7527783   0.78921333 -0.82991158]
 [-0.92189043 -0.66033916  0.75628501 -0.80330633]
 [-0.15778475  0.91577906  0.06633057  0.38375423]]
Random starting synaptic weights (layer 3): 
[[-0.36896874]
 [ 0.37300186]
 [ 0.66925134]
 [-0.96342345]]

New synaptic weights (layer 1) after training: 
[[-0.39042717  4.02220543 -1.52322523  2.40451717 -2.77177632]
 [-0.86817904 -0.33659723 -0.245578   -0.31292608  0.26079733]
 [-0.00600591 -1.69046817  0.12647375 -0.79367455  1.04614   ]]

New synaptic weights (layer 2) after training: 
[[ 0.9614375  -0.15372521 -0.67703076 -0.00498486]
 [-2.7714058   0.77

In [29]:
# test with new input
print("\nPredict new value [1,0,0]: ")
print(NN.run(np.array([1,0,0])))


Predict new value [1,0,0]: 
[ 0.99650838]
